---
sample_groups:
  37c: [2, 4]
  ice: [1, 3]
  with_triptolide: [3, 4]
  no_triptolide: [1, 2]
samples:
  1: "ice_no_t"
  2: "37c_no_t"
  3: "ice_t"
  4: "37c_t"
samples_longname:
  1: "ice_no_triptolide"
  2: "37c_no_triptolide"
  3: "ice_triptolide"
  4: "37c_triptolide"
hto_mapping_to_samples:
  1: 1
  2: 2
  3: 3
  4: 4
hto_mapping_to_samples_longname:
  hto1: "sample1"
  hto2: "sample2"
  hto3: "sample3"
  hto4: "sample4"
adhoc_dir: "data/adhoc/"
external_dir: "data/external/"
interim_dir: "data/interim/"
processed_dir: "data/processed/"
raw_dir: "data/raw/cellranger-mm10/"
report_dir: "reports/"
docs_dir: "docs/"
data_owner: "DB_AKC"
data_owner_longname: "David-Bryder_Anna-Konturek-Ciesla"
project_name: "DB_AKC_citeseq"
n_threads: 16
max_memory_to_use_in_gb: 60
seed: 12345
